apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.13.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: helm/values.yaml