apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: config-management-monitoring
  namespace: config-management-monitoring
spec:
  endpoints:
    - interval: 10s
      port: metrics
  namespaceSelector:
    matchNames:
      - config-management-monitoring
  selector:
    matchLabels:
      monitored: "true"
