apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics-system

resources:
  - namespace.yaml

helmCharts:
  - name: kube-prometheus-stack
    version: 51.2.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    namespace: metrics-system
    valuesFile: helm/values.yaml