crds:
  enabled: false

grafana:
  enabled: false

kubeEtcd:
  enabled: false

prometheus:
  prometheusSpec:
    scrapeConfigSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false