apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: cert-manager
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: git
  git:
    branch: main
    dir: cert-manager/base
    repo: https://github.com/johnjcool/kpt-bootstrap
    auth: none