apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: edge-os-upgrade
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  version:  0.0.4
  nodeSelector:
    matchExpressions:
      - key: elemental.cattle.io/image
        operator: Exists
  serviceAccountName: system-upgrade
  cordon: true
  #  drain:
  #    force: true
  upgrade:
    image: johnjcool/edge-os
    command:
      - "/usr/sbin/suc-upgrade"
